quarkus.qute.web.markdown.plugin.tables.enabled=false
quarkus.qute.web.markdown.plugin.autolink.enabled=false
quarkus.qute.web.markdown.plugin.heading-anchor.enabled=false
quarkus.qute.web.markdown.plugin.alerts.custom-types.INFO=Information
