= Quarkus Qute Web

include::./includes/attributes.adoc[]

The goal of this extension is to expose https://quarkus.io/guides/qute-reference[Qute] templates located in the `src/main/resource/templates/pub` directory via HTTP.
Automatically, no controllers needed. 
For example, the template `src/main/resource/templates/pub/foo.html` will be served from the paths `/foo` and `/foo.html` by default.

NOTE: The `index.html` and `index.qute.html` pages are handled specifically, i.e. they are also served as a "default page" of the containing directory. For example, the template `src/main/resource/templates/pub/index.html` will be served from the paths `/index`, `/index.html` and `/` by default.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.qute.web:quarkus-qute-web` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.qute.web</groupId>
    <artifactId>quarkus-qute-web</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Accessing Data

In a template you can access:

- https://quarkus.io/guides/qute-reference#injecting-beans-directly-in-templates[`@Named` CDI beans]; similar to EL; e.g. `{cdi:myBean.findItems()}`
- https://quarkus.io/guides/qute-reference#accessing-static-fields-and-methods[static members of a class] annotated with `@TemplateData`
- https://quarkus.io/guides/qute-reference#convenient-annotation-for-enums[enums] annotated with `@TemplateEnum`
- https://quarkus.io/guides/qute-reference#namespace_extension_methods[Namespace Extension Methods] in general
- https://quarkus.io/guides/qute-reference#global_variables[global variables]
- the current `io.vertx.core.http.HttpServerRequest` via the `http:` namespace, e.g. `{http:request.path}`
- the query parameters via the <<http_namespace,`http:` namespace>>, e.g. `{http:param('name')}` and `{http:param('name','Foo')}`

=== Data initializers

It is also possible to define a _data initializer_; a CDI bean that implements `io.quarkiverse.qute.web.DataInitializer`.
It can be used to initialize template data for specific pages, i.e. to set the data and attributes of a template instance for a given path.
The scope of an implementation must be `@Singleton` or `@ApplicationScoped`.

[source,java]
----
@Singleton
public class SimpleInitializer implements DataInitializer {

    @Override
    public void initialize(InitContext ctx) {
        if (ctx.path().endsWith("hello")) {
            ctx.templateInstance().data("name", "world");
        } 
    }
}
----

== Compression Support

If the HTTP compression support is enabled by means of `quarkus.http.enable-compression=true` then the response body is compressed if the `Content-Type` header derived from the template file name is a compressed media type as configured via `quarkus.http.compress-media-types`.


== Template Fragments

It is possible to specify the template fragment via the `frag` query param.
For example, if there is a template `foo.html` that defines a https://quarkus.io/guides/qute-reference#fragments[fragment] with id `bar` then the fragment is served from the path `/foo?frag=bar`.


== Content Negotiation

This extension attempts to serve the appropriate template and set the HTTP `Content-type` header based on the selected template variant and the value of `Accept` header.
For example, if there are templates `src/main/resource/templates/pub/foo.html` and `src/main/resource/templates/pub/foo.txt` and the client sends the `Accept: text/html, text/plain;q=0.9` header then `foo.html` is rendeder and the `Content-type: text/html` header is set.

[[http_namespace]]
== `http:` Namespace

Some useful https://quarkus.io/guides/qute-reference#namespace_extension_methods[template extension methods] that handle the `http` namespace are registered automatically.

|===
|Name|Description|Example

|`http:request`
|Returns the current `io.vertx.core.http.HttpServerRequest`
|`{http:request.path}`

|`http:param`
|Returns the first HTTP request query param value with the specified name
|`{http:param('page')}` or `{http:param('name', 'default value')}`

|`http:header`
|Return the first HTTP request header value with the specified name
|`{http:header('HX-Request')}`

|`http:headers`
|Makes it possible to access HTTP header values like properties
|`{http:headers.Accept-Encoding}` or `{http:headers.accept-encoding}`

|===

NOTE: HTTP header names are case-insensitive.

TIP: If you need to obtain all values of a specific HTTP header then you can use something similar to `{http:request.headers.getAll('My-Header')}`.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-qute-web.adoc[leveloffset=+1, opts=optional]
